---
- name: Проверка наличия Docker
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Create gitlab directories
  file: path={{ item }} recurse=yes state=directory
  with_items:
    - "/etc/docker/gitlab/config"
    - "/etc/docker/gitlab/logs"
    - "/etc/docker/gitlab/data"

- name: Запуск контейнера GitLab
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce:latest
    state: started
    restart_policy: always
    ports:
      - "56080:80"
      - "56443:443"
      - "2222:22"
    volumes:
      - /etc/docker/gitlab/config:/etc/gitlab
      - /etc/docker/gitlab/logs:/var/log/gitlab
      - /etc/docker/gitlab/data:/var/opt/gitlab
    env:
      GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
  become: yes
  vars:
    ansible_docker_use_system_connection: true
    docker_host: "unix:///var/run/docker.sock"

- name: deploy gitlab configuration
  template: src=gitlab.rb.j2 dest="/etc/docker/gitlab/config/gitlab.rb" owner=root group=root mode=0644
